//! Compile-time article store. Until the editorial CMS (WS2) wires a database,
//! published articles live here as data. An article may carry a self-hosted
//! `video` (drives the on-page player + og:video for inline social play) and/or
//! a `youtube` id (privacy-respecting youtube-nocookie embed) plus an `image`
//! (hero/thumbnail; for video pieces this is the video's thumbnail).

/// A self-hosted video attached to an article (served from /media; drives the
/// player + Open Graph video tags for rich social sharing).
#[derive(Clone, PartialEq)]
pub struct Video {
    pub mp4: &'static str,    // e.g. "/media/<slug>.mp4"
    pub poster: &'static str, // e.g. "/media/<slug>.jpg"
    pub width: u32,
    pub height: u32,
    pub duration_secs: u32,
}

#[derive(Clone, PartialEq)]
pub struct Article {
    pub slug: &'static str,
    pub title: &'static str,
    pub summary: &'static str,
    pub byline: &'static str,
    pub date: &'static str,            // human, e.g. "June 2026"
    pub iso_date: &'static str,        // for <time>/JSON-LD, e.g. "2026-06-14"
    pub kind: &'static str, // format: "Court report" | "Investigation" | "Announcement" | "Explainer"
    pub section: &'static str, // topical section: one of SECTIONS (Crime/Courts/Local/Community)
    pub body: &'static [&'static str], // paragraphs
    pub video: Option<Video>, // self-hosted video (og:video inline play)
    pub youtube: Option<&'static str>, // youtube id → youtube-nocookie embed
    pub image: Option<&'static str>, // hero/thumbnail (absolute URL or /path)
}

impl Article {
    /// On-site hero/thumbnail used in lists + at the top of the article.
    pub fn hero(&self) -> Option<&'static str> {
        self.image
    }
    /// Branded share card for Open Graph (generated by tools/og/gen.mjs).
    pub fn og_image(&self) -> String {
        format!("/og/news/{}.png", self.slug)
    }
}

/// Published articles, newest first.
pub const ARTICLES: &[Article] = &[
    Article {
        slug: "kieron-willans-guilty",
        section: "Crime",
        title: "Leicester man Kieron Willans sentenced over indecent images of children",
        summary: "Kieron Willans, from Leicester, has been given a suspended sentence after being found guilty of making indecent photographs of a child. He had been caught with more than 50 indecent images.",
        byline: "Scott Taylor",
        date: "May 2026",
        iso_date: "2026-05-21",
        kind: "Court report",
        body: &[
            "Kieron Willans, from Leicester, has been sentenced after being found guilty of two counts of making an indecent photograph of a child. He had been caught with more than 50 indecent images.",
            "He was given 18 weeks in prison, suspended for 18 months, with a 250-hour community order and \u{00a3}259 in costs, and was made subject to a five-year Sexual Harm Prevention Order.",
            "He is also moving to the Sheffield area.",
            "We reported the case from the court record. You can watch our report above.",
        ],
        video: Some(Video { mp4: "/media/kieron-willans.mp4", poster: "https://i.ytimg.com/vi/tqhkphyTjzo/hqdefault.jpg", width: 360, height: 640, duration_secs: 44 }),
        youtube: Some("tqhkphyTjzo"),
        image: Some("https://i.ytimg.com/vi/tqhkphyTjzo/hqdefault.jpg"),
    },
    Article {
        slug: "jamie-wallace-guilty",
        section: "Crime",
        title: "Jamie Wallace pleads guilty to 122 Category A child abuse images",
        summary: "Jamie Wallace has pleaded guilty to possessing 122 Category A indecent images of children, the most serious type. We put it to him.",
        byline: "Jordan Upton",
        date: "April 2026",
        iso_date: "2026-04-08",
        kind: "Court report",
        body: &[
            "Jamie Wallace has pleaded guilty to possessing 122 Category A indecent images of children. Category A is the most serious type there is.",
            "We put it to him and reported the case from the court record. You can watch our report above.",
        ],
        video: Some(Video { mp4: "/media/jamie-wallace.mp4", poster: "https://i.ytimg.com/vi/f-4rRYRo48c/hqdefault.jpg", width: 360, height: 640, duration_secs: 70 }),
        youtube: Some("f-4rRYRo48c"),
        image: Some("https://i.ytimg.com/vi/f-4rRYRo48c/hqdefault.jpg"),
    },
    Article {
        slug: "david-coote-convicted",
        section: "Crime",
        title: "Former Premier League referee David Coote convicted of child abuse image",
        summary: "David Coote, the former Premier League referee, has been convicted of making a Category A indecent image of a child and given a suspended sentence. We put it to him on camera.",
        byline: "Jordan Upton",
        date: "January 2026",
        iso_date: "2026-01-08",
        kind: "Court report",
        body: &[
            "David Coote, the former Premier League referee, has been convicted of making a Category A indecent image of a child, the most serious category recognised by the courts.",
            "Police visited his home on 13 February 2025 and recovered a laptop and a hard drive. On the hard drive was a Category A moving image of a child. He pleaded guilty.",
            "He was sentenced to nine months' imprisonment, suspended for two years, with 150 hours of unpaid work. He was made subject to a Sexual Harm Prevention Order for ten years and placed on the sex offenders register for ten years. The judge certified that he had been convicted of a sexual offence.",
            "The case has nothing to do with the earlier footage of him making comments about a Premier League manager, which had already cost him his refereeing career.",
            "We put it to him on camera. You can watch that above, and the sentencing remarks are public on the judiciary's website.",
        ],
        video: Some(Video { mp4: "/media/david-coote.mp4", poster: "https://i.ytimg.com/vi/h2AbTO7PEKE/hqdefault.jpg", width: 360, height: 640, duration_secs: 12 }),
        youtube: Some("h2AbTO7PEKE"),
        image: Some("https://i.ytimg.com/vi/h2AbTO7PEKE/hqdefault.jpg"),
    },
    Article {
        slug: "ben-fass-confronted-nuneaton",
        section: "Crime",
        title: "Convicted child sex offender Ben Fass confronted in Mansfield — now believed to be in Nuneaton",
        summary: "We tracked down a convicted child sex offender in Mansfield and put it to him about his life since release. Within days he was forced out of the area, and we now believe he has moved to Nuneaton.",
        byline: "Jordan Upton",
        date: "December 2025",
        iso_date: "2025-12-20",
        kind: "Investigation",
        body: &[
            "Ben Fass was convicted of child sex offences. After reports reached us about how he was behaving since, we tracked him to Mansfield and put it to him on camera.",
            "Within two days of the exposure, he was forced out of the area over his status as a convicted child sex offender. We now believe he has since moved to the Nuneaton area.",
            "We report on people once their case has ended, from the public record, and sometimes we go back to see what has happened since when there is good reason to.",
            "You can watch the report above.",
        ],
        video: Some(Video { mp4: "/media/ben-fass.mp4", poster: "https://i.ytimg.com/vi/kdC0NMqpRrI/hqdefault.jpg", width: 360, height: 640, duration_secs: 1320 }),
        youtube: Some("kdC0NMqpRrI"),
        image: Some("https://i.ytimg.com/vi/kdC0NMqpRrI/hqdefault.jpg"),
    },
    Article {
        slug: "predator-hunters-launches-its-newsroom",
        section: "Community",
        title: "Predator Hunters launches its newsroom",
        summary: "We are opening our newsroom: independent local reporting, court coverage from the public record, reward appeals for information on serious crimes, and a public conviction database. Here is what we do, and the standards you can hold us to.",
        byline: "Jordan Upton",
        date: "June 2026",
        iso_date: "2026-06-14",
        kind: "Announcement",
        body: &[
            "Our first major story was a murder. We published details the police had not, and afterwards officers came to us asking for our sources. We protected them, as we always will. That is what we are built on.",
            "More followed. In 2022 we reported that a social club in Derbyshire was selling alcohol to children. We have covered bailiffs and arrests at a local hospital, and decisions by a local council that left residents without homes. We break serious local news of all kinds, and since 2020 we have offered rewards for information that helps catch the people behind serious crimes.",
            "Today we are opening our newsroom properly.",
            "From here we will break local news of all kinds, not only the headline crimes. We will report concluded cases from the public court record. We are building a public database so a community can look up offenders who have been convicted, by name, area and offence. And where information can help bring someone to justice, we will keep appealing for it, with a reward.",
            "Some things will never change. We protect our sources. We keep them anonymous, and we only act on what we can stand up. As a rule we do not name anyone before they are charged, unless there is a strong public interest and we can confirm it. On the cases we cover, we stick to the record.",
            "We hold ourselves to a published standard, not a promise. We run a documented complaints procedure, we correct mistakes openly and keep both the original and the correction on the record, and we hold ourselves to the IMPRESS Standards Code and intend to seek registration with IMPRESS, the UK's approved press regulator. All of it is set out on our Standards page, and if you think we have got something wrong, we want to hear it and we will put it right.",
            "We were limited in what we could do in 2025. In 2026 this became a core part of who we are. We are independent and self-funded, and we work independently of any police force. If you have a story, information, or want to support the work, get in touch. If a child is in immediate danger, call 999.",
        ],
        video: None,
        youtube: None,
        image: None,
    },
    Article {
        slug: "how-we-report",
        section: "Community",
        title: "How we report, and the lines we won't cross",
        summary: "How a group known for confronting offenders can also be a publisher people trust: we keep the frontline work and the reporting apart, and we never name anyone before a charge.",
        byline: "Jordan Upton",
        date: "June 2026",
        iso_date: "2026-06-14",
        kind: "Explainer",
        body: &[
            "People ask us, fairly, how a group known for confronting offenders can also be a newsroom people trust. Here is how we work.",
            "We do the frontline work, and we report, but we keep the two apart. What we choose to publish is a separate decision, made later, to a different standard.",
            "As a rule we do not name anyone before they are charged. Before a charge, an accusation can wreck an innocent life and collapse a real case, so we hold back unless there is a strong public interest and we can confirm the facts, such as a named suspect in a murder or other serious crime, or a confirmed arrest.",
            "We hold footage back until there is a conviction. When we do publish it, we censor what needs censoring, and we only run it when it teaches people something real. We are not in it for a show.",
            "We report from the public court record, after a case has concluded, and we check what we write against that record. If we get something significantly wrong, we correct it promptly and with the same prominence as the original, and we keep both on the record.",
            "We hold ourselves to the IMPRESS Standards Code and intend to seek registration, so these are not just our promises but a published standard you can hold us to.",
        ],
        video: None,
        youtube: None,
        image: None,
    },
    Article {
        slug: "why-a-public-conviction-database",
        section: "Community",
        title: "Why we built a public conviction database",
        summary: "Court records are public but scattered. We think a community has a right to see what the courts have decided, in one place, in plain terms, drawn from the public record.",
        byline: "Jordan Upton",
        date: "June 2026",
        iso_date: "2026-06-14",
        kind: "Explainer",
        body: &[
            "Court records are public, but they are scattered. A conviction reported one afternoon in one courtroom is, in practice, almost impossible for an ordinary person to find again. We think a community has a right to see what the courts have decided, in one place, in plain terms.",
            "So we are building a public conviction database. You will be able to search by name, area or offence and find people who have been convicted, with the facts drawn from the public court record.",
            "It is bound by the same lines as everything else we do. Every entry comes only after a conviction, never while a case is live and never before a charge. Every entry is checked against the court record before it goes up. It is a record of what the courts have already decided in public, not an accusation of our own.",
            "There is no photo upload and no face search on the public side. You search with words, and you see the court's findings.",
            "If you believe an entry is wrong, out of date, or that something needs correcting or removing, you can tell us and we will check it against the record. We handle this data under UK data-protection law, with a documented basis and a clear route to have an entry reviewed.",
        ],
        video: None,
        youtube: None,
        image: None,
    },
];

pub fn by_slug(slug: &str) -> Option<&'static Article> {
    ARTICLES.iter().find(|a| a.slug == slug)
}

/// Topical sections, in front-page display order. The home + news pages render
/// from these dynamically, so adding an article with a section (here or, later,
/// via the CMS) populates the section automatically — no layout code to touch.
pub const SECTIONS: &[&str] = &["Crime", "Courts", "Local", "Community"];

/// Published articles in a section, newest first (ARTICLES is already newest-first).
pub fn in_section(section: &str) -> Vec<&'static Article> {
    ARTICLES.iter().filter(|a| a.section == section).collect()
}

/// A public conviction-database entry. Drawn from a concluded court case and
/// linked to the news report. `lat`/`lng` are 0.0 when the court did not state a
/// place (those entries simply carry no map pin). This is the news<->database
/// crossover: every entry here is also a published court report.
#[derive(Clone, PartialEq)]
pub struct Conviction {
    pub name: &'static str,
    pub area: &'static str, // town/city, or "" if not stated in court
    pub offence: &'static str,
    pub outcome: &'static str, // sentence summary
    pub date: &'static str,
    pub iso_date: &'static str,
    pub article: &'static str, // slug of the linked news report
    pub lat: f64,
    pub lng: f64,
}

impl Conviction {
    pub fn located(&self) -> bool {
        self.lat != 0.0 || self.lng != 0.0
    }
}

/// Convictions we have reported, drawn from the public court record. Newest first.
pub const CONVICTIONS: &[Conviction] = &[
    Conviction {
        name: "Kieron Willans",
        area: "Leicester",
        offence: "Making indecent photographs of a child",
        outcome: "18 weeks in prison suspended for 18 months, a 250-hour community order, and a 5-year Sexual Harm Prevention Order",
        date: "May 2026",
        iso_date: "2026-05-21",
        article: "kieron-willans-guilty",
        lat: 52.6369,
        lng: -1.1398,
    },
    Conviction {
        name: "Jamie Wallace",
        area: "",
        offence: "Possessing 122 Category A indecent images of children",
        outcome: "Pleaded guilty; awaiting sentence",
        date: "April 2026",
        iso_date: "2026-04-08",
        article: "jamie-wallace-guilty",
        lat: 0.0,
        lng: 0.0,
    },
    Conviction {
        name: "David Coote",
        area: "",
        offence: "Making a Category A indecent image of a child",
        outcome: "9 months suspended for 2 years, 150 hours unpaid work, a 10-year Sexual Harm Prevention Order, and the sex offenders register for 10 years",
        date: "January 2026",
        iso_date: "2026-01-08",
        article: "david-coote-convicted",
        lat: 0.0,
        lng: 0.0,
    },
    Conviction {
        name: "Ben Fass",
        area: "Mansfield",
        offence: "Child sex offences",
        outcome: "Convicted; subject to ongoing reporting requirements",
        date: "December 2025",
        iso_date: "2025-12-20",
        article: "ben-fass-confronted-nuneaton",
        lat: 53.1437,
        lng: -1.1969,
    },
];
